spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AsTheStarsFall/spring-cloud-config.git
          search-paths: # 可以搜索SC-CONFIG目录下所有满足条件的配置文件
            - SC-CONFIG
  application:
    name: sc-config-git
server:
  port: 9090
