spring:
  application:
    name: gateway-zuul-apollo
server:
  port: 9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    client-apollo:
      path: /client/** #相当于/client_new/**
      serviceId: config-client-apollo #相当于config-client-apollo2
apollo:
  bootstrap:
    enabled: true
    namespaces: TEST1.zuul-config
  meta: http://localhost:8080
