spring:
  application:
    name: zuul-server
server:
  port: 5555
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8888}/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    client:
      #满足path匹配规则的请求，映射到url
      path: /client/**
      #服务发现的应用的名称
      service-url: client
  ratelimit:
    key-prefix: springcloud-study #按粒度拆分的临时变量key前缀
    enabled: true #启用开关
    repository: IN_MEMORY #key存储类型，默认是IN_MEMORY本地内存，此外还有多种形式
    behind-proxy: true #表示代理之后
    default-policy: #全局限流策略，可单独细化到服务粒度
      # TODO 在3秒的时间窗口内不能有超过两次的接口调用
      limit: 2 #在一个单位时间窗口的请求数量
      quota: 1 #在一个单位时间窗口的请求时间限制
      refresh-interval: 3 #单位时间窗口
      type:
        - user #可指定用户粒度
        - origin #可指定客户端地址粒度
        - url #可指定url粒度
