server:
  port: 7070
spring:
  application:
    name: client
eureka:
  client:
    service-url:
      #×¢²áµ½eureka server
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8888}/eureka/
  instance:
    #½«IP×¢²áµ½eureka server
    prefer-ip-address: true
